In [2]:
from sklearn.feature_extraction.text import CountVectorizer

text=['I have a little daughter', 'Mary had a little lamp', 'Twinkle twinkle little star' 'The silence of lamps']

#Initialize the vector
vectorizer=CountVectorizer()

#transform
x=vectorizer.fit_transform(text)

#get feature names (words)

feature_names=vectorizer.get_feature_names_out()

#Display BOW-Matrix

print('Feature names: \n', feature_names)
print()
print('BOW Matrix: \n')
print(x.toarray())

Feature names: 
 ['daughter' 'had' 'have' 'lamp' 'lamps' 'little' 'mary' 'of' 'silence'
 'starthe' 'twinkle']

BOW Matrix: 

[[1 0 1 0 0 1 0 0 0 0 0]
 [0 1 0 1 0 1 1 0 0 0 0]
 [0 0 0 0 1 1 0 1 1 1 2]]


In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer

text=['I have a little daughter', 'Mary had a little lamp', 'Twinkle twinkle little star','The silence of lamps']

tfidf=TfidfVectorizer()
x_tfidf=tfidf.fit_transform(text)

features_names_tfidf=tfidf.get_feature_names_out()

print('Feature Names(TF-IDF):\n', features_names_tfidf)
print()
print('TF-IDF Matrix:\n', x_tfidf.toarray())

Feature Names(TF-IDF):
 ['daughter' 'had' 'have' 'lamp' 'lamps' 'little' 'mary' 'of' 'silence'
 'star' 'the' 'twinkle']

TF-IDF Matrix:
 [[0.64450299 0.         0.64450299 0.         0.         0.41137791
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.5417361  0.         0.5417361  0.         0.34578314
  0.5417361  0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.27448674
  0.         0.         0.         0.43003652 0.         0.86007303]
 [0.         0.         0.         0.         0.5        0.
  0.         0.5        0.5        0.         0.5        0.        ]]


In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize import sent_tokenize

text=input('Enter a statement: \n\t')
sent_token=sent_tokenize(text)
print('Sentences: \n', sent_token)

for sent in sent_token:
    print(sent)
    print(len(sent))
print()

tfidf=TfidfVectorizer()
x_tfidf=tfidf.fit_transform(sent_token)

features_names_tfidf=tfidf.get_feature_names_out()

print('Feature Names(TF-IDF):\n',features_names_tfidf)
print()
print('TF-IDF Matrix:\n', x_tfidf.toarray())

Enter a statement: 
	Alice opened the door and found that it led into a small passage, not much larger than a rat-hole: she knelt down and looked along the passage into the loveliest garden you ever saw.
Sentences: 
 ['Alice opened the door and found that it led into a small passage, not much larger than a rat-hole: she knelt down and looked along the passage into the loveliest garden you ever saw.']
Alice opened the door and found that it led into a small passage, not much larger than a rat-hole: she knelt down and looked along the passage into the loveliest garden you ever saw.
182

Feature Names(TF-IDF):
 ['alice' 'along' 'and' 'door' 'down' 'ever' 'found' 'garden' 'hole' 'into'
 'it' 'knelt' 'larger' 'led' 'looked' 'loveliest' 'much' 'not' 'opened'
 'passage' 'rat' 'saw' 'she' 'small' 'than' 'that' 'the' 'you']

TF-IDF Matrix:
 [[0.1490712 0.1490712 0.2981424 0.1490712 0.1490712 0.1490712 0.1490712
  0.1490712 0.1490712 0.2981424 0.1490712 0.1490712 0.1490712 0.1490712
  0.1490712 

In [10]:
import nltk
from nltk import ngrams

text='It is used in natural language processing'
tokens=nltk.word_tokenize(text)

#Generate bigrams

n=2
bigrams=list(ngrams(tokens,n))

print(f"Original text: {text}")
print()
print(f"Generated {n}-grams:") 
for gram in bigrams:
    print(gram)

Original text: It is used in natural language processing

Generated 2-grams:
('It', 'is')
('is', 'used')
('used', 'in')
('in', 'natural')
('natural', 'language')
('language', 'processing')


In [11]:
#Generate bigrams

n=3
bigrams=list(ngrams(tokens,n))

print(f"Original text: {text}")
print()
print(f"Generated {n}-grams:") 
for gram in bigrams:
    print(gram)

Original text: It is used in natural language processing

Generated 3-grams:
('It', 'is', 'used')
('is', 'used', 'in')
('used', 'in', 'natural')
('in', 'natural', 'language')
('natural', 'language', 'processing')


In [12]:
#Generate bigrams

n=4
bigrams=list(ngrams(tokens,n))

print(f"Original text: {text}")
print()
print(f"Generated {n}-grams:") 
for gram in bigrams:
    print(gram)

Original text: It is used in natural language processing

Generated 4-grams:
('It', 'is', 'used', 'in')
('is', 'used', 'in', 'natural')
('used', 'in', 'natural', 'language')
('in', 'natural', 'language', 'processing')


In [15]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

text=['I have a little daughter', 'Mary had a little lamp', 'Twinkle twinkle little star','The silence of lamps']

#step 1- tokens
tokens=[word for sent in text for word in sent.lower().split()]

#step 2- vocabulary
vocabulary=list(set(tokens))# unique words in the text


#initialize encoder
encoder=OneHotEncoder(categories=[vocabulary], sparse=False)

#Perform the one-hot encoding

one_hot_encoded=[]
for sent in text:
    sent_encoded=[]
    for word in sent.lower().split():
        word_index=vocabulary.index(word)
        word_vector=np.zeros(len(vocabulary))
        word_vector[word_index]=1
        sent_encoded.append(word_vector)
    one_hot_encoded.append(sent_encoded)

for sent in one_hot_encoded:
    print(sent)
      

[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])]
[array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]), array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])]
[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]), array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])]
[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]), array([0., 0., 0., 0.

In [16]:
sent[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.])

In [17]:
sent[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.])

In [18]:
len(sent)

4

In [19]:
type(sent)

list

In [20]:
!pip install gensim

     ---------------------------------------- 0.0/67.1 kB ? eta -:--:--
     ------------------------ --------------- 41.0/67.1 kB ? eta -:--:--
     ---------------------------------------- 67.1/67.1 kB 1.8 MB/s eta 0:00:00
  Obtaining dependency information for simpful from https://files.pythonhosted.org/packages/8d/93/8448d3f1aa9d2911b8cba2602aaa1af85eb31a26d28b7b737f1fa5b40c02/simpful-2.11.1-py3-none-any.whl.metadata
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for fst-pso: filename=fst_pso-1.8.1-py3-none-any.whl size=20448 sha256=1e0edad13aa515d8e4d20dce88305132807adce19f0c8069155b956d3e80e59b
  Stored in directory: c:\users\thama\appdata\local\pip\cache\wheels\69\f5\e5\18ad53fe1ed6b2af9fad05ec052e4acbac8e92441df44bad2e
  Created wheel for miniful: filename=miniful-0.0.6-py3-none-any.whl size=3522 sha256=5f69

In [21]:
import gensim
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize
import nltk

#sample text

text=['Word embeddings capture semantic relationships',
      'Word2vec is a popular technique in nlp',
      'Word embedding model in a continuos vector space']
tokenized_text=[word_tokenize(sentence.lower()) for sentence in text]

#Train Word2vec model
model=Word2Vec(sentences=tokenized_text, vector_size=20,window=5,min_count=1, workers=4)

#Find word vectors
vector_semantic=model.wv['semantic']
vector_nlp=model.wv['nlp']

#similarity b/w words

similarity=model.wv.similarity('word', 'embeddings')

print(f"Vector for 'semantic': {vector_semantic}")
print('-'*100)
print(f"Vector for 'nlp': {vector_nlp}")
print('='*100)
print(f"Similarity b/w 'word' and 'embeddings': {similarity}")

Vector for 'semantic': [-0.04309844  0.01832869  0.02594942  0.02870969  0.03733459 -0.03083838
  0.00552807  0.03023641 -0.01420025 -0.03086761 -0.00205112 -0.04184474
 -0.02800006  0.03552269  0.0167627   0.03612835  0.03400124  0.03765371
 -0.01894577 -0.00280903]
----------------------------------------------------------------------------------------------------
Vector for 'nlp': [-0.02797029  0.00865183 -0.00448686  0.03396846  0.01986795  0.02264736
  0.00717153 -0.01349928 -0.02183406 -0.00516037  0.00718514 -0.01323004
 -0.03536891 -0.03902654 -0.04560893 -0.02967585 -0.00923712 -0.02161936
 -0.03230335 -0.01858661]
Similarity b/w 'word' and 'embeddings': 0.05595846474170685


In [23]:
from gensim.models import Doc2Vec
from gensim.models.doc2vec import TaggedDocument
from nltk.tokenize import word_tokenize

#sample text

documents=['Word embeddings capture semantic relationships',
           'Word2vec is a popular technique in nlp',
           'Word embedding model in a continuos vector space']

#Tokenize & tag documents

tagged_data=[TaggedDocument(words=word_tokenize (doc.lower()), tags=[str(i)]) for i, doc in enumerate(documents)]
print(tagged_data)

[TaggedDocument(words=['word', 'embeddings', 'capture', 'semantic', 'relationships'], tags=['0']), TaggedDocument(words=['word2vec', 'is', 'a', 'popular', 'technique', 'in', 'nlp'], tags=['1']), TaggedDocument(words=['word', 'embedding', 'model', 'in', 'a', 'continuos', 'vector', 'space'], tags=['2'])]


In [26]:
model=Doc2Vec(vector_size=100,window=2,min_count=1,workers=5, epochs=20)
model.build_vocab(tagged_data)
model.train(tagged_data, total_examples=model.corpus_count,epochs=model.epochs)

In [27]:
vector_doc_1=model.infer_vector(word_tokenize('Word embeddings capture semantic relationships',
                                              'Word2vec is a popular technique in nlp',
                                              'Word embedding model in a continuos vector space'))

In [28]:
vector_doc_1

array([-3.6035238e-03, -1.9890747e-03,  4.3723667e-03,  2.1197842e-03,
       -6.7712725e-05, -2.5892216e-03, -3.6983327e-03,  3.0281511e-03,
        4.7519491e-03, -4.5778174e-03, -1.3389792e-03,  1.9155790e-05,
        2.6954620e-03, -4.2717978e-03, -1.3793741e-03, -2.0585854e-03,
       -1.1760993e-03, -2.1583568e-03,  9.9848374e-04, -3.0819490e-03,
        1.9066416e-03, -3.2890358e-03,  4.2215837e-03,  3.7146220e-03,
        4.1005143e-04, -2.7608136e-03, -2.8819701e-04, -2.0332194e-03,
       -1.3203814e-03,  1.9238092e-03,  1.3767395e-04, -4.3475330e-03,
        4.6175951e-03,  1.3399654e-03,  2.4797942e-03,  4.4075740e-03,
        2.1847708e-03,  6.8986526e-05,  3.5275938e-03,  7.6590572e-04,
       -2.4242576e-03, -4.4040424e-03, -4.1932845e-03, -3.0207334e-03,
        4.0450739e-03,  1.0521623e-03, -4.3028896e-03, -1.5824392e-03,
       -2.1688592e-04, -3.3605201e-03, -1.9021380e-03,  1.5187864e-03,
       -4.7570956e-03,  3.3617199e-03, -3.3516674e-03, -3.1365503e-03,
      

In [30]:
#find the most similar document

similar_doc=model.docvecs.most_similar(positive=[vector_doc_1])

print(f"vector for 'Word embeddings capture semantic relationships': {vector_doc_1}")
print()
print(f"Most similar document: {similar_doc}")

vector for 'Word embeddings capture semantic relationships': [-3.6035238e-03 -1.9890747e-03  4.3723667e-03  2.1197842e-03
 -6.7712725e-05 -2.5892216e-03 -3.6983327e-03  3.0281511e-03
  4.7519491e-03 -4.5778174e-03 -1.3389792e-03  1.9155790e-05
  2.6954620e-03 -4.2717978e-03 -1.3793741e-03 -2.0585854e-03
 -1.1760993e-03 -2.1583568e-03  9.9848374e-04 -3.0819490e-03
  1.9066416e-03 -3.2890358e-03  4.2215837e-03  3.7146220e-03
  4.1005143e-04 -2.7608136e-03 -2.8819701e-04 -2.0332194e-03
 -1.3203814e-03  1.9238092e-03  1.3767395e-04 -4.3475330e-03
  4.6175951e-03  1.3399654e-03  2.4797942e-03  4.4075740e-03
  2.1847708e-03  6.8986526e-05  3.5275938e-03  7.6590572e-04
 -2.4242576e-03 -4.4040424e-03 -4.1932845e-03 -3.0207334e-03
  4.0450739e-03  1.0521623e-03 -4.3028896e-03 -1.5824392e-03
 -2.1688592e-04 -3.3605201e-03 -1.9021380e-03  1.5187864e-03
 -4.7570956e-03  3.3617199e-03 -3.3516674e-03 -3.1365503e-03
  3.0580475e-03  7.0992764e-04  3.1076751e-03  8.8644918e-04
  4.2397375e-03  4.16339

C:\Users\thama\AppData\Local\Temp\ipykernel_15480\3566639832.py:3: DeprecationWarning: Call to deprecated `docvecs` (The `docvecs` property has been renamed `dv`.).
  similar_doc=model.docvecs.most_similar(positive=[vector_doc_1])
