In [3]:
import numpy as np
#Dataset
np_olympic_country=np.array(['GBR', 'Chine', 'RUS', 'US', 'KOR', 'JPN', 'GER'])
np_olympic_country_gold=np.array([29,38,24,46,13,7,11]) 
np_olympic_country_silver=np.array([17, 28, 25, 28,8,14,11])
np_olympic_country_Bronze=np.array([19,22,32,29,7,17,14])

# find the country index with maximum gold


In [5]:
max_gold_index=np.argmax(np_olympic_country_gold)
print(max_gold_index)

3


# Print Country with Maximum gold


In [6]:
country_with_max_gold=np_olympic_country[max_gold_index]
print(country_with_max_gold)

US


# Find countries with more than 20 gold

In [8]:
countries_with_more_than_20_gold = np_olympic_country[np_olympic_country_gold > 20]
print("Countries with more than 20 gold:", countries_with_more_than_20_gold)


Countries with more than 20 gold: ['GBR' 'Chine' 'RUS' 'US']


# 1. print each country name with number of gold medals   2. print each country name with total number of medals

In [9]:
import numpy as np

# Dataset
olympic_country = np.array(['GBR', 'China', 'RUS', 'US', 'KOR', 'JPN', 'GER'])
olympic_country_gold = np.array([29, 38, 24, 46, 13, 7, 11])
olympic_country_silver = np.array([17, 28, 25, 28, 8, 14, 11])
olympic_country_bronze = np.array([19, 22, 32, 29, 7, 17, 14])

# 1. Print each country name with the number of gold medals
for i in range(len(olympic_country)):
    print(f"Country: {olympic_country[i]}, Gold Medals: {olympic_country_gold[i]}")

# 2. Print each country name with the total number of medals
total_medals = olympic_country_gold + olympic_country_silver + olympic_country_bronze
for i in range(len(olympic_country)):
    print(f"Country: {olympic_country[i]}, Total Medals: {total_medals[i]}")


Country: GBR, Gold Medals: 29
Country: China, Gold Medals: 38
Country: RUS, Gold Medals: 24
Country: US, Gold Medals: 46
Country: KOR, Gold Medals: 13
Country: JPN, Gold Medals: 7
Country: GER, Gold Medals: 11
Country: GBR, Total Medals: 65
Country: China, Total Medals: 88
Country: RUS, Total Medals: 81
Country: US, Total Medals: 103
Country: KOR, Total Medals: 28
Country: JPN, Total Medals: 38
Country: GER, Total Medals: 36


# Create a 3x3x3 array with random values


In [20]:
import numpy as np

# Create a 3x3x3 array with random values between 1 and 10
random_array = np.random.randint(1,10, (3, 3, 3))

print(random_array)


[[[6 6 6]
  [7 4 2]
  [2 4 5]]

 [[4 4 9]
  [4 2 8]
  [4 3 8]]

 [[7 9 9]
  [2 2 5]
  [4 1 7]]]


# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal


In [21]:
import numpy as np

# Create a 5x5 matrix with values 1, 2, 3, and 4 below the diagonal
matrix = np.diag([1, 2, 3, 4], k=-1)

print(matrix)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# Create a 8x8 matrix and fill it with a checkerboard pattern


In [28]:
import numpy as np

# Create an 8x8 checkerboard pattern matrix
checkerboard = np.zeros((8, 8), dtype=int)

# Fill the odd-indexed rows and columns with 1
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Normalize a 5x5 random matrix


In [41]:
import numpy as np

# Create a random 5x5 matrix
random_matrix = np.random.randint(1,11,(5, 5))

# Calculate the mean and standard deviation of the matrix
mean = np.mean(random_matrix)
std_dev = np.std(random_matrix)
print(mean)
print(std_dev)

4.88
2.7323250172700906


In [42]:
# Normalize the matrix
normalized_matrix = (random_matrix - mean) / std_dev

print("Random Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)

Random Matrix:
[[ 2  3  4  2  1]
 [ 4  7  1  4  3]
 [ 4  7  9  8 10]
 [ 8  7  6  8  5]
 [ 1  8  6  2  2]]

Normalized Matrix:
[[-1.05404737 -0.6880587  -0.32207003 -1.05404737 -1.42003604]
 [-0.32207003  0.77589598 -1.42003604 -0.32207003 -0.6880587 ]
 [-0.32207003  0.77589598  1.50787332  1.14188465  1.87386199]
 [ 1.14188465  0.77589598  0.40990731  1.14188465  0.04391864]
 [-1.42003604  1.14188465  0.40990731 -1.05404737 -1.05404737]]


# How to find common values between two arrays?


In [43]:
import numpy as np

# Define two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find common values between the two arrays
common_values = np.intersect1d(array1, array2)

print("Common values between array1 and array2:", common_values)


Common values between array1 and array2: [3 4 5]


# How to get the dates of yesterday, today and tomorrow?


In [44]:
import numpy as np
import datetime

# Get the current date as a numpy datetime64 object
today = np.datetime64('today')

# Calculate yesterday and tomorrow
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

# Convert numpy datetime64 objects to Python datetime objects (optional)
yesterday_date = yesterday.astype(datetime.datetime)
today_date = today.astype(datetime.datetime)
tomorrow_date = tomorrow.astype(datetime.datetime)

print("Yesterday:", yesterday_date)
print("Today:", today_date)
print("Tomorrow:", tomorrow_date)


Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


# Consider two random array A and B, check if they are equal

In [53]:
import numpy as np

# Create two random arrays A and B
A = np.random.randint(5)
B = np.random.randint(5)

# Check if the arrays A and B are equal
are_equal = np.array_equal(A, B)

if are_equal:
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")


Arrays A and B are equal.


# Create random vector of size 10 and replace the maximum value by 0

In [57]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value in the vector
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Random vector with the maximum value replaced by 0:")
print(random_vector)


Random vector with the maximum value replaced by 0:
[0.25840087 0.2060263  0.33833158 0.14063325 0.77843523 0.6875566
 0.33790017 0.36777741 0.52014512 0.        ]


# How to print all the values of an array?


In [58]:
import numpy as np

# Create a NumPy array
my_array = np.array([1, 2, 3, 4, 5])

# Print all values using the print() function
print(my_array)


[1 2 3 4 5]


# Subtract the mean of each row of a matrix


In [59]:
import numpy as np

# Create a sample matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Calculate the row-wise mean
row_means = np.mean(matrix, axis=1, keepdims=True)

# Subtract the row-wise mean from the matrix
matrix_normalized = matrix - row_means

print("Original Matrix:")
print(matrix)
print("\nMatrix with Row-wise Mean Subtracted:")
print(matrix_normalized)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix with Row-wise Mean Subtracted:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [60]:
row_means = np.mean(matrix, axis=1, keepdims=True)
print(row_means)

[[2.]
 [5.]
 [8.]]


# Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?


In [61]:
import numpy as np

# Given vector
given_vector = np.array([1, 2, 3, 4, 5])

# Second vector with indices to be modified
indices_to_add_1 = np.array([1, 3, 1, 4])

# Create an array of zeros with the same shape as the given_vector
result_vector = np.zeros_like(given_vector)

# Use np.add.at to add 1 to the elements at specified indices
np.add.at(result_vector, indices_to_add_1, 1)

print("Given Vector:", given_vector)
print("Modified Vector:", result_vector)


Given Vector: [1 2 3 4 5]
Modified Vector: [0 2 0 1 1]


# How to get the diagonal of a dot product?


In [62]:
import numpy as np

# Create two matrices A and B
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Calculate the dot product of A and B
dot_product = np.dot(A, B)

# Get the diagonal of the dot product
diagonal = np.diag(dot_product)

print("Diagonal of the Dot Product:")
print(diagonal)


Diagonal of the Dot Product:
[30 69 90]


# How to find the most frequent value in an array?


In [67]:
import numpy as np

# Create a sample NumPy array
array = np.array([1, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5])

# Use np.bincount to count occurrences of each value
counts = np.bincount(array)

# Find the value with the maximum count
most_frequent_value = np.argmax(counts)

print("Most frequent value:", most_frequent_value)


Most frequent value: 3


# How to get the n largest values of an array


In [69]:
import numpy as np

# Create a sample NumPy array
array = np.array([10, 2, 8, 6, 7, 3, 5, 1, 9, 4])

# Set the value of n (number of largest values you want)
n = 1

# Use numpy.partition to get the n largest values
n_largest_values = np.partition(array, -n)[-n:]

print(f"The {n} largest values are:", n_largest_values)


The 1 largest values are: [10]


# How to create a record array from a regular array?

In [70]:
import numpy as np

# Create a regular array
regular_array = np.array([(1, 'charlie', 30),
                          (2, 'rohit', 25),
                          (3, 'virat', 35)],
                         dtype=[('ID', int), ('Name', 'U10'), ('Age', int)])

# Display the regular array
print("Regular Array:")
print(regular_array)

# Access elements in the regular array
print("\nAccessing elements in the regular array:")
print("First element:", regular_array[0])
print("Name of the second element:", regular_array[1]['Name'])

# Create a record array
record_array = np.rec.array(regular_array)

# Display the record array
print("\nRecord Array:")
print(record_array)

# Access elements in the record array
print("\nAccessing elements in the record array:")
print("First element:", record_array[0])
print("Name of the second element:", record_array[1].Name)


Regular Array:
[(1, 'charlie', 30) (2, 'rohit', 25) (3, 'virat', 35)]

Accessing elements in the regular array:
First element: (1, 'charlie', 30)
Name of the second element: rohit

Record Array:
[(1, 'charlie', 30) (2, 'rohit', 25) (3, 'virat', 35)]

Accessing elements in the record array:
First element: (1, 'charlie', 30)
Name of the second element: rohit


# How to swap two rows of an array?


In [85]:
import numpy as np

# Create a sample 2D array (matrix)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Swap rows (e.g., swap rows 0 and 1)
matrix[0, :], matrix[1, :] = matrix[1, :].copy(), matrix[0, :].copy()

# Display the matrix after swapping
print("Matrix after swapping rows 0 and 1:")
print(matrix)


Matrix after swapping rows 0 and 1:
[[4 5 6]
 [1 2 3]
 [7 8 9]]


# Write python code to reshape to the next dimension of numpy array?


In [83]:
import numpy as np

# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6])

# Reshape it to the next dimension (2D)
array_2d = array_1d.reshape(-1, 2)

# Display the reshaped array
print("Original 1D Array:")
print(array_1d)

print("\nReshaped 2D Array:")
print(array_2d)


Original 1D Array:
[1 2 3 4 5 6]

Reshaped 2D Array:
[[1 2]
 [3 4]
 [5 6]]
